rewrite ^about-2/$ about/ permanent;
rewrite ^bottom/$  permanent;
rewrite ^computer-repair-booroobin/$ computer-repairs-booroobin/ permanent;
rewrite ^computer-repair-chuwar/$ computer-repairs-chuwar-ui/ permanent;
rewrite ^computer-repairs-berrinba-lc/$ computer-repairs-berrinba/ permanent;
rewrite ^computer-repairs-cedar-creek-2/$ computer-repairs-cedar-creek/ permanent;
rewrite ^computer-repairs-ridgewood-2/$ computer-repairs-ridgewood/ permanent;
rewrite ^computer-repairs-surfers-paradise-2/$ computer-repairs-surfers-paradise/ permanent;
rewrite ^computer-repairs-surfers-paradise-3/$ computer-repairs-surfers-paradise/ permanent;
rewrite ^contact-2/$ contact/ permanent;
rewrite ^contact-us/$ contact/ permanent;
rewrite ^home-2/$  permanent;
rewrite ^homepage/$  permanent;
rewrite ^laptop-repair/$ laptop-repairs/ permanent;
rewrite ^laptop-repairs-holland-park-qld-4121/$ laptop-repairs-holland-park/ permanent;
rewrite ^mac-repairs-cedar-creek-qld-4520/$ mac-repairs-cedar-creek-qld-4207/ permanent;
rewrite ^mac-repairs-chuwar-qld-4306/$ mac-repairs-chuwar-qld-4306-2/ permanent;
rewrite ^mac-repairs-sinnamon-park-qld-4073/$ mac-repairs-sinnamon-park-qld-4073-2/ permanent;
rewrite ^pc-repairs-cedar-creek-qld-4520/$ pc-repairs-cedar-creek-qld-4207/ permanent;
rewrite ^pc-repairs-chuwar-qld-4306/$ pc-repairs-chuwar-qld-4306-2/ permanent;
rewrite ^pc-repairs-sinnamon-park-qld-4073/$ pc-repairs-sinnamon-park-qld-4073-2/ permanent;
rewrite ^services/virus-malware-and-spyware-removal-brisbane/$ virus-malware-and-spyware-removal-brisbane/ permanent;
rewrite ^virus-removal/$ virus-malware-and-spyware-removal-brisbane/ permanent;
